version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: fullstack_development
      MYSQL_USER: fahadkhan
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
#      configuring the db while using not locally but from an image
  fahadkhan-api:
    container_name: fahadkhan-api
    image: fadialfa/fahadkhan-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/fullstack_development
    ports:
      - "8088:8080"
    networks:
      - app-network
    depends_on:
      - mysql
    restart: unless-stopped


networks:
  app-network:
volumes:
  mysql_data:
