name: CI - Build Backend
on:
  pull_request:
    branches:
      - main
    paths:
      - backend/**

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_PASSWORD: 123456
          MYSQL_USER: fahadkhan
          MYSQL_DATABASE: fullstack_development
        ports:
          - 3306:3307
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - uses: actions/setup-java@v4.6.0



        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build and run test
        run: mvn -ntp -B verify





